/*
MIT License

Copyright (c) 2020 PriceRunner

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
/* 
 * Merchant API
 *
 * Endpoints for getting information regarding merchants.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Model
{
    /// <summary>
    /// Request Parameter
    /// </summary>
    [DataContract]
    public partial class MerchantSkus :  IEquatable<MerchantSkus>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantSkus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MerchantSkus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantSkus" /> class.
        /// </summary>
        /// <param name="merchantSkus">merchantSkus (required).</param>
        public MerchantSkus(List<string> merchantSkus = default(List<string>))
        {
            // to ensure "merchantSkus" is required (not null)
            if (merchantSkus == null)
            {
                throw new InvalidDataException("merchantSkus is a required property for MerchantSkus and cannot be null");
            }
            else
            {
                this._MerchantSkus = merchantSkus;
            }
        }
        
        /// <summary>
        /// merchantSkus
        /// </summary>
        /// <value>merchantSkus</value>
        [DataMember(Name="merchantSkus", EmitDefaultValue=false)]
        public List<string> _MerchantSkus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MerchantSkus {\n");
            sb.Append("  _MerchantSkus: ").Append(_MerchantSkus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MerchantSkus);
        }

        /// <summary>
        /// Returns true if MerchantSkus instances are equal
        /// </summary>
        /// <param name="input">Instance of MerchantSkus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MerchantSkus input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._MerchantSkus == input._MerchantSkus ||
                    this._MerchantSkus != null &&
                    this._MerchantSkus.SequenceEqual(input._MerchantSkus)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._MerchantSkus != null)
                    hashCode = hashCode * 59 + this._MerchantSkus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
