/*
MIT License

Copyright (c) 2020 PriceRunner

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
/* 
 * Merchant API
 *
 * Endpoints for getting information regarding merchants.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Model
{
    /// <summary>
    /// A collection of Product Listing
    /// </summary>
    [DataContract]
    public partial class ProductListingsV1 :  IEquatable<ProductListingsV1>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductListingsV1" /> class.
        /// </summary>
        /// <param name="productListings">List of all products matching queries.</param>
        public ProductListingsV1(List<ProductListingV1> productListings = default(List<ProductListingV1>))
        {
            this.ProductListings = productListings;
        }
        
        /// <summary>
        /// List of all products matching queries
        /// </summary>
        /// <value>List of all products matching queries</value>
        [DataMember(Name="productListings", EmitDefaultValue=false)]
        public List<ProductListingV1> ProductListings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductListingsV1 {\n");
            sb.Append("  ProductListings: ").Append(ProductListings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductListingsV1);
        }

        /// <summary>
        /// Returns true if ProductListingsV1 instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductListingsV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductListingsV1 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProductListings == input.ProductListings ||
                    this.ProductListings != null &&
                    this.ProductListings.SequenceEqual(input.ProductListings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProductListings != null)
                    hashCode = hashCode * 59 + this.ProductListings.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
