/*
MIT License

Copyright (c) 2020 PriceRunner

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
/* 
 * Merchant API
 *
 * Endpoints for getting information regarding merchants.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Model
{
    /// <summary>
    /// Containing Product information and current Offers
    /// </summary>
    [DataContract]
    public partial class ProductListingV1 :  IEquatable<ProductListingV1>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductListingV1" /> class.
        /// </summary>
        /// <param name="offers">List of details on offers.</param>
        /// <param name="product">Details of the product.</param>
        public ProductListingV1(List<OfferV1> offers = default(List<OfferV1>), ProductV1 product = default(ProductV1))
        {
            this.Offers = offers;
            this.Product = product;
        }
        
        /// <summary>
        /// List of details on offers
        /// </summary>
        /// <value>List of details on offers</value>
        [DataMember(Name="offers", EmitDefaultValue=false)]
        public List<OfferV1> Offers { get; set; }

        /// <summary>
        /// Details of the product
        /// </summary>
        /// <value>Details of the product</value>
        [DataMember(Name="product", EmitDefaultValue=false)]
        public ProductV1 Product { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductListingV1 {\n");
            sb.Append("  Offers: ").Append(Offers).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductListingV1);
        }

        /// <summary>
        /// Returns true if ProductListingV1 instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductListingV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductListingV1 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Offers == input.Offers ||
                    this.Offers != null &&
                    this.Offers.SequenceEqual(input.Offers)
                ) && 
                (
                    this.Product == input.Product ||
                    (this.Product != null &&
                    this.Product.Equals(input.Product))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Offers != null)
                    hashCode = hashCode * 59 + this.Offers.GetHashCode();
                if (this.Product != null)
                    hashCode = hashCode * 59 + this.Product.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
